"""
Primary population dynamics simulation code (mathematical model).
"""

from oncosim.cell_state import CellState, validate_states, json_load_cell_states
from oncosim.drug_models import DrugProtocol, drug_time_points, concentration_ode

import numpy as np
import pandas as pd

DRUGS = {
    "doxorubicin": {"half_life_days": 0.5},
    "paclitaxel": {"half_life_days": 1.5},
    "cisplatin": {"half_life_days": 0.8},
    "no_drug": {"half_life_days": np.inf}} # creating some supported drugs for the simulator

def simulation(
        states: dict,
        initial_counts: dict,
        drug_name: str,
        dose_um: float,
        dose_interval_days: float,
        carrying_capacity: float,
        duration_days: float) -> dict:
    
    if drug_name not in DRUGS:
        raise ValueError(f"Drug '{drug_name}' not found in drug models.")
    
    state_names = list(states.keys())
    n_states = len(state_names)
    idx = {state: i for i, state in enumerate(state_names)}

    k_elim = np.log(2) / DRUGS[drug_name]["half_life_days"]
    
    # The block of code, used to create a transition matrix, was AI generated by Claude.
    # AI was used due to lack of expertise and knowledge from faculty lab members.

    transition_matrix = np.zeros((n_states, n_states))
    for state, transitions in states.items():
        i = idx[state]
        for target, probability in state.transitions.items():
            transition_matrix[idx[state], idx[target]] = probability
    
    y0 = [float(initial_counts.get(name, 0)) for name in state_names] + [0.0]
 
    dose_times = (
        np.arange(0, duration_days, dose_interval_days).tolist()
        if drug_name != "no_treatment" else []
    )
    breakpoints = sorted(set([0.0] + dose_times + [duration_days]))
